### ISSUE TITLE
When text description is too long buttons are hidden

### ISSUE THREAD

**Issue by Nikoloutsos** [TecOrb-Developers/SmartAlertDialog#2]
When text description is too long buttons are hidden.
I think if you let the user scroll it would be way better.

In the photo there are 2 button. One positive and one negative. But user can see all of them!

![image](https://user-images.githubusercontent.com/14034942/81701190-5915b980-9472-11ea-9947-4a328e050428.png)

**Comment by TecOrb-Developers** [comment]
thanks for your suggestion, i will update it soon

**Comment by TecOrb-Developers** [comment]
> thanks for your suggestion, i will update it soon



> When text description is too long buttons are hidden.
> I think if you let the user scroll it would be way better.
> 
> In the photo there are 2 button. One positive and one negative. But user can see all of them!
> 
> ![image](https://user-images.githubusercontent.com/14034942/81701190-5915b980-9472-11ea-9947-4a328e050428.png)

fixed the issue
